person:
  userName: zhangsan
  boss: true
  birth: 2002/1/3
  age: 23
  pet: 阿狗
  interests:
    - 篮球
    - 足球
    - 网球
  animal:
    - 猪猪
    - 猫咪
    - 狗狗
  score:
    english: 60
    math: 78

  salarys:
    - 333
    - 4335
    - 6335
  allPets:
    sick:
      - {name: 翠花,weight: 34}
      - name: 威威
      - weight: 32
    health: [{name: 忍者,weight: 23},{name: 飞侠,weight: 34}]

