spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&CharacterEncoding=utf-8
    username: 'root'
    password: '123456'
mybatis:
  config-location: classpath:mybatis/MbConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true  #开启驼峰