spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&CharacterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: 'root'
    password: '123456'

    druid:
      #配置监控控制功能开启,并设置用户名和密码
      stat-view-servlet:
          enabled: true
          login-username: root
          login-password: 12345
      #配置web-jdbc关联监控的数据
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      #底层开启功能 stat(sql监控) wall(防火墙)
      filters: stat,wall

      #监控SpringBean
      aop-patterns: com.boot.config.*



